// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrasi & CLI (migrate, studio, db pull) memakai koneksi LANGSUNG
    // Supabase (port 5432). Runtime aplikasi memakai koneksi pooled
    // (DATABASE_URL) lewat driver adapter di src/lib/prisma.ts.
    url: process.env["DIRECT_URL"],
  },
});
