// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "pnpm tsx prisma/seed.ts",
  },
  datasource: {
    // Migrations and CLI tools use a direct Supabase connection (port 5432).
    // The runtime app uses a pooled connection (DATABASE_URL) via the adapter
    // in src/lib/prisma.ts.
    url: process.env["DIRECT_URL"],
  },
});
